package exception_file.org;

public class ExceptionDemo2 {

	public static void main(String[] args) throws ArrayIndexOutOfBoundsException, NegativeArraySizeException, ArithmeticException, Exception 
			{
		// TODO Auto-generated method stub
		int[] marks = {98,95,100,94};
	//	try
	//	{
		Throwdemo.display(marks);
		//}
		//catch(ArrayIndexOutOfBoundsException aa)
		//{
		//	System.out.println("CHeck array");
		//}
	}

}
