package exception_file.org;

import java.util.Scanner;

public class Exception1{
	public static void main(String[] args) {
		//Scanner sc=new Scanner(System.in);//input mismatch exception, runtime not given proper value
		//boolean nb=sc.nextBoolean();
		//System.out.println(nb);
		
		//Arithmatic Exception
		System.out.println(10);
		System.out.println(20);
		System.out.println(30);
		//try {
		System.out.println(4/0);// try catch exception
		//}
		//catch(ArithmeticException e)
		//{
			//System.out.println("THis is Arithmatic exception");
		//}
		
		//System.out.println(50);
		
		
		//index out of bond exception
		/*int[] a=new int[5];
		a[0]=12;
		a[1]=13;
		a[2]=14;
		a[3]=15;
		a[4]=16;
		a[5]=17;
		a[6]=18;*/
		
		/*try
		{
			System.out.println(4/0);
		}
		catch(Exception e)
		{
			System.out.println("Exception");
		}*/
	}

}
